services:
  - type: web
    name: selenium-app
    env: python
    envVars:
      - key: CHROME_BIN
        value: /opt/render/project/src/chrome/opt/google/chrome/chrome
    buildCommand: |
      pip install -r requirements.txt
      curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      mkdir -p chrome
      dpkg -x google-chrome-stable_current_amd64.deb chrome
      rm google-chrome-stable_current_amd64.deb
      chmod +x chrome/opt/google/chrome/chrome
    startCommand: gunicorn app:app
