services:
  - type: web
    name: selenium-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser chromium-chromedriver
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: RENDER
        value: "true"
