services:
  - type: web
    name: selenium-app
    env: python
    pythonVersion: "3.10"
    packages:
      - chromium-browser
      - chromium-chromedriver
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: "true"
